# Grid layout
GRID_ROWS = 4
GRID_COLS = 4
CELL_SIZE = 100
GRID_PADDING = 20
GRID_ORIGIN_X = 300
GRID_ORIGIN_Y = 40

# Cube layout
CUBE_SIZE = 64
CUBE_GAP = 16
START_AREA_X = 40
START_AREA_Y = 40

# Card/hand display area
CARD_AREA_X = GRID_ORIGIN_X
CARD_AREA_Y = GRID_ORIGIN_Y + GRID_ROWS * CELL_SIZE + 30
CARD_AREA_W = GRID_COLS * CELL_SIZE

# Hand rules
HAND_LIMIT = 8

# Hand rendering (2 rows x 4 cols)
HAND_ROWS = 2
HAND_COLS = 4
HAND_SLOT_W = 70
HAND_SLOT_H = 92
HAND_SLOT_GAP_X = 18
HAND_SLOT_GAP_Y = 14
HAND_TOP_PAD = 40
HAND_BOTTOM_PAD = 24

# Height needed to fully contain the hand area:
CARD_AREA_H = HAND_TOP_PAD + HAND_ROWS * HAND_SLOT_H + (HAND_ROWS - 1) * HAND_SLOT_GAP_Y + HAND_BOTTOM_PAD


