# Grid layout
GRID_ROWS = 4
GRID_COLS = 4
CELL_SIZE = 100
GRID_PADDING = 20
GRID_ORIGIN_X = 300
GRID_ORIGIN_Y = 40

# Cube layout
CUBE_SIZE = 64
CUBE_GAP = 16
START_AREA_X = 40
START_AREA_Y = 40

# Card display area
CARD_AREA_X = GRID_ORIGIN_X
CARD_AREA_Y = GRID_ORIGIN_Y + GRID_ROWS * CELL_SIZE + 30
CARD_AREA_W = GRID_COLS * CELL_SIZE
CARD_AREA_H = 100
